jenkins:
  extends:
    file: docker-compose-template.yml
    service: jenkins
  volumes:
    - ../:/var/dev_repo:ro # Clone this RO so as to guarentee we never touch dev files.
    - ./jenkins/jenkins_home:/var/jenkins_home 
    - /var/run/docker.sock:/var/run/docker.sock
